name: Matrix Build with Artifacts

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.9', '3.10', '3.11']

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: matrix-0a49356
        run: echo "Building for Python ${{ matrix.python-version }}"

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Generate build artifact
        run: echo "Build output for Python ${{ matrix.python-version }}" > output.txt

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-0a49356-v${{ matrix.python-version }}
          path: output.txt
